// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMVvnGTmfM-2BbEx05qQFD1f9e8wcn9Cc',
    appId: '1:514939435570:web:6b1e6367c1f662c8301a2b',
    messagingSenderId: '514939435570',
    projectId: 'my-subscription-manage',
    authDomain: 'my-subscription-manage.firebaseapp.com',
    storageBucket: 'my-subscription-manage.firebasestorage.app',
    measurementId: 'G-5SGC78SM9Y',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOouCr-V4sc4FTVZ9mCKJIcvDu2f3VYTg',
    appId: '1:514939435570:ios:6c2fd7fadcdf1499301a2b',
    messagingSenderId: '514939435570',
    projectId: 'my-subscription-manage',
    storageBucket: 'my-subscription-manage.firebasestorage.app',
    iosBundleId: 'com.example.sabakan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOouCr-V4sc4FTVZ9mCKJIcvDu2f3VYTg',
    appId: '1:514939435570:ios:6c2fd7fadcdf1499301a2b',
    messagingSenderId: '514939435570',
    projectId: 'my-subscription-manage',
    storageBucket: 'my-subscription-manage.firebasestorage.app',
    iosBundleId: 'com.example.sabakan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMVvnGTmfM-2BbEx05qQFD1f9e8wcn9Cc',
    appId: '1:514939435570:web:492350a6571dd664301a2b',
    messagingSenderId: '514939435570',
    projectId: 'my-subscription-manage',
    authDomain: 'my-subscription-manage.firebaseapp.com',
    storageBucket: 'my-subscription-manage.firebasestorage.app',
    measurementId: 'G-W1SJG22489',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl3BZtXUmk6WJJCHHiM4lzd26ZgS65wq0',
    appId: '1:514939435570:android:398dd7e4a28151ea301a2b',
    messagingSenderId: '514939435570',
    projectId: 'my-subscription-manage',
    storageBucket: 'my-subscription-manage.firebasestorage.app',
  );

}